fix: add the needed rust bridge code to link the python ai and the ru…
Prophecy-eip/Maths pull request #164
Opened 2023-10-24 01:25 UTC by H4ss

…st with a call in the main.rs, and added a flask server for the ai to receive the rust requests.

Only thing needed is now to update the swagger and ensure that a flask server runs with the library

2023-10-24 19:39 UTC, Jordan-B1 requested changes

2023-10-24 19:39 UTC, Jordan-B1 commented on src/ai_integration/implement_route.rs
> +    Ok((50, 50))
Rather than (50, 50)
You should throw an error like ```unreachable!()```
At first I was like "wait....what is 50 already ?"

2023-10-24 19:39 UTC, Jordan-B1 commented on src/main.rs
> +        Ok((50, 50)) => {
As you'll throw an unreachable, you will not have to handle this here

2023-10-24 19:39 UTC, Jordan-B1 commented on src/web_server/mod.rs
> +    /// Add a unit to the first player's army
You forgot the description of the param && return value

2023-10-24 19:39 UTC, Jordan-B1 commented on src/web_server/mod.rs
> +    /// Add a unit to the second player's army
You forgot the description of the param && return value

2023-10-25 00:20 UTC, Pepiloto requested changes

2023-10-25 00:20 UTC, Pepiloto commented on src/ai_integration/implement_route.rs
> +                let target_sum = 20;
Isn't the target sum always 20 ?

2023-10-25 00:20 UTC, Pepiloto commented on src/ai_integration/implement_route.rs
> +fn adjust_values(val1: f64, val2: f64, target_sum: u8) -> (u8, u8) {
Isn't the target sum always 20 ?

2023-10-25 00:20 UTC, Pepiloto commented on src/main.rs
> +pub mod ai_integration;
Under the rules pls

2023-10-25 00:20 UTC, Pepiloto commented on src/main.rs
> +        Ok((50, 50)) => {
What is 50, 50 ?

2023-10-25 00:20 UTC, Pepiloto commented on src/ai_integration/implement_route.rs
> +    Ok((50, 50))
What is 50,50 ?

2023-10-25 00:20 UTC, Pepiloto commented on src/main.rs
> +    match ai_integration::implement_route::poc_flask(regiment.0).await {
Is it only one regiment ?

2023-10-25 00:20 UTC, Pepiloto commented on src/main.rs
> +    match ai_integration::implement_route::poc_flask(regiment.0).await {
If not it's not clear

2023-10-25 00:20 UTC, Pepiloto commented on src/web_server/mod.rs
> +    second_player: Vec<ProphecyUnit>,
```suggestion
    first_player_army: Vec<ProphecyUnit>,
    second_player_army: Vec<ProphecyUnit>,
```

2023-10-25 00:20 UTC, Pepiloto commented on src/web_server/mod.rs
> +    /// Modifiers : list of String for the modifiers linked to the unit
Missing types

2023-10-25 00:20 UTC, Pepiloto commented on src/web_server/mod.rs
> +    /// second player : a list of defending prophecy units
Missing types

2023-10-25 00:20 UTC, Pepiloto commented on src/web_server/mod.rs
> +        second_player: Vec<ProphecyUnit>,
```suggestion
        first_player_army: Vec<ProphecyUnit>,
        second_player_army: Vec<ProphecyUnit>,
```

2023-10-25 00:20 UTC, Pepiloto commented on src/web_server/mod.rs
> +    /// &String: The key name
Not the right documentation

2023-10-25 00:20 UTC, Pepiloto commented on src/web_server/mod.rs
> +    /// &String: The key name
Not the right documentation

2023-10-25 00:20 UTC, Pepiloto commented on src/web_server/mod.rs
> +    /// Add a unit to the first player's army
Doc imcomplete

2023-10-25 00:20 UTC, Pepiloto commented on src/web_server/mod.rs
> +    /// Add a unit to the second player's army
Doc imcomplete

2023-10-31 00:20 UTC, Pepiloto requested changes

2023-10-31 00:20 UTC, Pepiloto commented on src/ai_integration/implement_route.rs
> +/// target_sum (u8): The sum that we want to reach
Missing parameter in function declaration

2023-10-31 00:20 UTC, Pepiloto commented on src/web_server/mod.rs
> +}
Should be closer to impl part for this struct

2023-10-31 00:20 UTC, Pepiloto commented on src/web_server/mod.rs
> +impl ProphecyRequestArmies {
Should be closer to struct declaration

2023-10-31 00:20 UTC, Pepiloto commented on src/web_server/mod.rs
> +    }
Why ?

2023-11-01 16:16 UTC, Jordan-B1 approved these changes

2023-11-04 14:31 UTC, Pepiloto requested changes

2023-11-04 14:31 UTC, Pepiloto commented on src/ai_integration/implement_route.rs
> +/// req: web_server::ProphecyRequestArmies
```suggestion
/// req (web_server::ProphecyRequestArmies): Request ...
```

2023-11-04 14:31 UTC, Pepiloto commented on src/ai_integration/implement_route.rs
> +pub async fn poc_flask(req: web_server::ProphecyRequestArmies) -> Result<(u8, u8)> {
Name of function doesn't start with a verb like handle_request, ...

2023-11-04 14:31 UTC, Pepiloto commented on src/ai_integration/implement_route.rs
> +    let url = "http://127.0.0.1:4242/predict";
Maybe a file with constants values ?

2023-11-04 14:31 UTC, Pepiloto commented on src/web_server/mod.rs
> +    second_player: Vec<ProphecyUnit>,
```suggestion
    first_player_army: Vec<ProphecyUnit>,
    second_player_army: Vec<ProphecyUnit>,
```

2023-11-06 10:44 UTC, Jordan-B1 submitted a review, later dismissed

2023-11-06 22:27 UTC, Pepiloto submitted a review, later dismissed

2023-11-06 22:31 UTC, Jordan-B1 approved these changes

2023-11-06 22:32 UTC, Pepiloto approved these changes

2023-11-06 22:40 UTC, merged