Test/clean tu
Prophecy-eip/Maths pull request #73
Opened 2022-12-06 10:36 UTC by TheVengeur

2022-12-06 14:58 UTC, Pepiloto requested changes
Format: Use the imperative mood in the subject line: "If applied, this commit will _your subject line here_"
It's in the Contributing.md file.
Your first commit is still not compliant with the Conventional Commit norm we use this pull request **will not be merged**.

2022-12-12 09:51 UTC, Jordan-B1 requested changes

2022-12-12 09:51 UTC, Jordan-B1 commented on src/global_test/mod.rs
> +    /// Stats Model: The Stats Model created and initialized
/!\ "The Stats Model", I'm not sure that I get this, maybe go for something like this
The Stats created and initialized

2022-12-12 09:51 UTC, Jordan-B1 commented on src/global_test/mod.rs
> +    /// Stats Model: The Stats Model created and initialized
"Our mock Stats struct" seems a better description for the "Return" field
because "The Stats Model"  kindof disturb me

2022-12-12 09:51 UTC, Jordan-B1 commented on src/global_test/mod.rs
> +    /// Stats Model: The Stats Model created and initialized
/!\ You're not creating a Stats Model here, you're creating a modifier' stats

2022-12-12 09:51 UTC, Jordan-B1 commented on src/global_test/mod.rs
> +    /// Stats Model: The Stats Model created and initialized
Stats Model :x:

2022-12-12 10:01 UTC, Jordan-B1 commented
You was not there when we created it, but we have a norm for the function comments. It goes like this

    /// Function description
    ///
    /// ## Parameters
    /// (PARAM_TYPE) PARAM_NAME : DESCRIPTION
    ///
    /// (PARAM_TYPE) PARAM_NAME : DESCRIPTION
    ///
    /// (PARAM_TYPE) PARAM_NAME : DESCRIPTION
    ///
    /// (PARAM_TYPE) PARAM_NAME : DESCRIPTION
    ///
    /// ## Return
    /// TYPE: DSCRIPTION

2023-01-01 15:18 UTC, TheVengeur commented
i don't know why my first commit don't want to change and why it add more commit...

2023-01-03 15:35 UTC, closed without merging