Chore/swagger
Prophecy-eip/Maths pull request #78
Opened 2022-12-30 23:26 UTC by Pepiloto

2023-01-01 13:43 UTC, TheVengeur approved these changes

2023-01-01 17:47 UTC, H4ss approved these changes

2023-01-27 12:03 UTC, Jordan-B1 requested changes
There's a typo in the "stat" data_structure and the examples. there is an 'S' at "health_pointS"

It might be confusing that the regiments in then examples have 20 rows, 20 columns and 100models (should be 400 then)

2023-01-27 15:30 UTC, TheVengeur approved these changes

2023-01-27 15:37 UTC, Jordan-B1 approved these changes

2023-01-27 15:59 UTC, merged